global:
  scrape_interval: 15s
  evaluation_interval: 30s
# scrape_timeout is set to the global default (10s).
rule_files:
  - "tanglebeat.rules"

scrape_configs:
  - job_name: "tanglebeat"
    static_configs:
      - targets: ["tanglebeat:8082"] # the address of an application that exposes metrics for prometheus
